### ISSUE TITLE
Not really a bug just wanted to reach out

### ISSUE THREAD

**Issue by BonkWomble** [SaltContainer/NEO-TWEWY-Randomizer#5]
3 things.

Firstly, thank you for creating this as I've had this project in the back of my mind for a while.

2.) I see that the only options currently available are for noise drops, story rewards and pin stats. Do you plan on finishing the rest of the menu? If no would you be willing to show me how to pick it up from where you left off?

Lastly, I am trying to get this to work on the steam version of the game and run into this error when trying to open the 4017d8fc.unity3d file
"
There was an error reading or decompressing one of the data files. Full Exception: The output char buffer is too small to contain the decoded character, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. Parameter name: chars
"
Any idea of how to make this work?
Please let me know if you are open to continuing this conversation preferably over discord.

**Comment by SaltContainer** [comment]
This was a bug related to PC support, this has been resolved in #6.

**Comment by SixtyMixty** [comment]
Hi! i also just wanted to reach out an express my thanks for creating and sharing the randomizer with us. Cant wait for the other planned features. Didnt wonna open a new issue so ill just comment here. thanks a bunch!
